AplikacjaMVC/HorseInfo/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Repository.IRepo;
using Repository.Models;
using Repository.Models.Views;

namespace HorseInfo.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventRepo _repo;

        public EventController(IEventRepo repo)
        {
            _repo = repo;
        }

        // GET: Event/Id
        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
                return RedirectToAction("Index", "Home");

            Event @event = _repo.GetEventById(id.Value);
            if (@event == null)
                return RedirectToAction("Index", "Home");

            EventDetailsViewModel viewModel = new EventDetailsViewModel
            {
                ev = @event,
                Annoucements = _repo.GetAnnoucements().AsNoTracking<Announcement>()
                                     .Where(o => o.EventId == id.Value).ToList<Announcement>()
            };
            return View(viewModel);
        }

        public ActionResult Organizer(int? id)
        {
            if (!id.HasValue)
                return RedirectToAction("Index", "Home");

            Event @event = _repo.GetEventById(id.Value);
            if (@event == null)
                return RedirectToAction("Index", "Home");

            return View(@event);
        }

        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Description")] Event @event)
        {
            if (!ModelState.IsValid)
                return View(@event);

            @event.UserId = User.Identity.GetUserId();
            @event.CreationDate = DateTime.Now;
            @event.Date = DateTime.Now.AddDays(5);
            try
            {
                _repo.AddEvent(@event);
                _repo.SaveChanges();
                //TODO return RedirectToAction("MyEvents"); stworzyć tę akcję i faktycznie do niej przekierować
                return RedirectToAction("Index", "Home");
            }
            catch(Exception ex)
            {
                Debug.WriteLine(ex.Message);
                return View(@event);
            }
        }
        
        public ActionResult Map(int? id)
        {
            if (!id.HasValue)
                return RedirectToAction("Index", "Home");

            Event @event = _repo.GetEventById(id.Value);
            if (@event == null)
                return RedirectToAction("Index", "Home");

            return View(@event);
        }
    }
}

AplikacjaMVC/HorseInfo/Views/Event/Create.cshtml
@model Repository.Models.Event

@{
    ViewBag.Title = "Dodaj ogłoszenie";
    ViewBag.Description = "Lista ogłoczesz z aplikacji - metaopis 160 znaków";
    ViewBag.KeyWords = " Lista, ogłoszeń, słowa, kluczowe, aplikacja";
}

<h2>Nowe</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home", null, new { @class = "btn btn-warning" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AplikacjaMVC/HorseInfo/Views/Event/Details.cshtml
@using Microsoft.AspNet.Identity;
@model Repository.Models.Views.EventDetailsViewModel

@{
    ViewBag.Description = "Jakiś opis detali " + Model.ev.Id;
    ViewBag.KeyWords = "Jakieś, słowa, kluczowe " + Model.ev.Id;
}

<div data-role="navbar">
    <ul>
        <li>@Html.ActionLink("Informacje", "Details", @Model.ev.Id, new { @class = "ui-btn-active" })</li>
        <li>@Html.ActionLink("Organizator", "Organizer", new { id = Model.ev.Id }, null)</li>
    </ul>
</div> @*navbar*@

<br />

<div>
    <div class="eventfield">
        <h3 id="modelTitle">
            @Html.DisplayFor(model => model.ev.Title)
        </h3>

        <hr />
        <p>@Html.DisplayFor(model => model.ev.Date)</p>
        <p>@Html.DisplayFor(model => model.ev.User.Company.CompanyAddress)</p>
        <p>@Html.DisplayFor(model => model.ev.Description)sratatataaaaaaaaaaaaaa aaaaaaaaaatttaaaaaaaaaaaaa</p>
        <p class="dateright">
            @Html.DisplayNameFor(model => model.ev.CreationDate)
            @Html.DisplayFor(model => model.ev.CreationDate)
        </p>
    </div>

    <br />

    <div class="eventfield">
        <table>
            <tr>
                <td>
                    <button type="button" onclick=" location.href='@Url.Action("Index", "Home", null)' " class=" ui-btn eventbut">
                        Wyniki
                    </button>
                </td>
                <td>
                    <button type="button" onclick=" location.href='@Url.Action("Index", "Home", null)' " class=" ui-btn eventbut">
                        Program
                    </button>
                </td>
            </tr>
        </table>

    </div>

    <h4>Komunikaty</h4>



    <div class="eventfield">
        <ul data-role="listview" class="eventfield">
            @foreach (var item in Model.Annoucements)
            {
                <li style="white-space:normal">
                    <br />
                    @Html.DisplayFor(modelItem => item.Content)
                    kghhhhhhhhhhhhhhhhhhhhhhhhhhfyyyy
                    yyyyyyyyyyyyyyyyyyyyyyyyyuuuuuuuuu

                    <p class="ui-li-aside">@Html.DisplayFor(modelItem => item.CreationDate)</p>
                </li>
                <br />
            }
        </ul>
    </div>
</div>
<p>
    @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker") || Model.ev.UserId == User.Identity.GetUserId()))
    {
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.ev.Id }, new { @class = "btn btn-primary" })
        @: |
    }
    @Html.ActionLink("Wróć", "Index", "Home", new { data_rel = "back" })
</p>





@*<dl >
        <dt>
            @Html.DisplayNameFor(model => model.ev.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ev.User.UserName)
        </dd>
    </dl>*@

AplikacjaMVC/HorseInfo/Views/Event/Map.cshtml
@model Repository.Models.Event

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Map</title>


    <script>
    function initialize() {
        var myLatlng = new google.maps.LatLng( @Model.User.Company.Lattitude, @Model.User.Company.Longitude );
            var myOptions = {
                zoom: 10,
                center: myLatlng,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            var map = new google.maps.Map( document.getElementById( "map_canvas" ), myOptions );

            var point  = new google.maps.LatLng(@Model.User.Company.Lattitude,@Model.User.Company.Longitude);
            var markerOptions =
            {
                position: point,
                map: map,
                title: "Tu jesteśmy"
            }
            var marker = new google.maps.Marker(markerOptions);
        }
    </script>
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <style>
        html {
            height: 100%;
            overflow: hidden;
        }

        body {
            margin: 0;
            padding: 0;
            height: 100%;
        }

        #map_canvas {
            height: 100%;
        }
    </style>
</head>
<body onload="initialize()">

    <div id="map_canvas"></div>

</body>
</html>

AplikacjaMVC/HorseInfo/Views/Event/Organizer.cshtml
@model Repository.Models.Event


<script>
    function scale(width, height, padding, border) {
        var scrWidth = $(window).width() - 30,
            scrHeight = $(window).height() - 30,
            ifrPadding = 2 * padding,
            ifrBorder = 2 * border,
            ifrWidth = width + ifrPadding + ifrBorder,
            ifrHeight = height + ifrPadding + ifrBorder,
            h, w;

        if (ifrWidth < scrWidth && ifrHeight < scrHeight) {
            w = ifrWidth;
            h = ifrHeight;
        } else if ((ifrWidth / scrWidth) > (ifrHeight / scrHeight)) {
            w = scrWidth;
            h = (scrWidth / ifrWidth) * ifrHeight;
        } else {
            h = scrHeight;
            w = (scrHeight / ifrHeight) * ifrWidth;
        }

        return {
            'width': w - (ifrPadding + ifrBorder),
            'height': h - (ifrPadding + ifrBorder)
        };
    };

    $(document).on("pageinit", function () {
        $("#OpenMap").click(function () {
            $("#popupMap iframe")
                .attr("width", 0)
                .attr("height", 0);

            $("#popupMap iframe").contents().find("#map_canvas")
                .css({ "width": 0, "height": 0 });

            $("#popupMap").on({
                popupbeforeposition: function () {
                    var size = scale(480, 320, 0, 1),
                        w = size.width,
                        h = size.height;

                    $("#popupMap iframe")
                        .attr("width", w)
                        .attr("height", h);

                    $("#popupMap iframe").contents().find("#map_canvas")
                        .css({ "width": w, "height": h });
                },
                popupafterclose: function () {
                    $("#popupMap iframe")
                        .attr("width", 0)
                        .attr("height", 0);

                    $("#popupMap iframe").contents().find("#map_canvas")
                        .css({ "width": 0, "height": 0 });
                }
            });
        });
    });
</script>

@{
    ViewBag.Title = "Organizer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div data-role="navbar">
    <ul>
        <li>@Html.ActionLink("Informacje", "Details", new { id = Model.Id })</li>
        <li>@Html.ActionLink("Organizator", "Organizer", @Model.Id, new { @class = "ui-btn-active" })</li>
    </ul>
</div> @*navbar*@

<div>
    <div>
        <table>
            <tr>
                <td>
                    <img src="@Url.Content("~/Content/no_image.png")" style="width: 100%; max-width: 200px" />
                </td>
                <td>
                    <h3>
                        @Html.DisplayFor(model => model.User.Company.CompanyName)
                    </h3>
                    @Html.DisplayFor(model => model.User.Company.HomepageUrl)
                    <br />
                    Tel.:
                    @Html.DisplayFor(model => model.User.Company.PhoneNumber)
                </td>
            </tr>
        </table>
    </div>
    <div style="width: 100%; margin: auto;">
        @Html.DisplayFor(model => model.User.Company.CompanyAddress)
        @*<div id="mapka">
                <!-- tu będzie mapa -->
            </div>*@
    </div>
    <div>
        <h4>O organizatorze:</h4>
        @Html.DisplayFor(model => model.User.Company.CompanyDescription)
    </div>

</div>

<!--Przycisk otwierajacy mapę-->

<a href="#popupMap" id="OpenMap" data-rel="popup" data-position-to="window" data-role="button" data-theme="b" data-inline="true">Pokaż mapę</a>

<div data-role="popup" id="popupMap" data-overlay-theme="a" data-theme="a" data-corners="false" data-tolerance="15,15">

    @*Przycisk "Zamknij" do mapy, brzydki jakiś
        <a href="#" data-rel="back" data-role="button" data-theme="b" data-icon="delete" data-iconpos="notext" class="ui-btn ui-btn-right" style="max-width: 10px; max-height: 10px; vertical-align: central;" >Zamknij</a>*@

    <iframe src='@Url.Action("Map", "Event", new { id = Model.Id })' width="480" height="320" seamless></iframe>

</div>